<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>symbols.txt</string>
	</array>
	<key>name</key>
	<string>decomp-toolkit symbols.txt tmLanguage</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>([^\s=]+)\s*(=)\s*</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.symbol.dtk-symbols</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.dtk-symbols</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>meta.symbol.dtk-symbols</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#address</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#attributes</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>address</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\.init|extab(?:index)?|\.(?:text|[cd]tors|(?:ro)?data|bss|s?(?:data|bss)2?))\s*(:)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.section.dtk-symbols constant.language.section.dtk-symbols</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.dtk-symbols</string>
						</dict>
					</dict>
					<key>end</key>
					<string>;</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.terminator.dtk-symbols</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.symbol.address.dtk-symbols</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#numbers</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\S+)\s*(:)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.section.dtk-symbols</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.dtk-symbols</string>
						</dict>
					</dict>
					<key>end</key>
					<string>;</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.terminator.dtk-symbols</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.symbol.address.dtk-symbols</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#numbers</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>attributes</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>//</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.dtk-symbols comment.line.double-slash.dtk-symbols</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$</string>
					<key>name</key>
					<string>meta.symbol.attribute-list.dtk-symbols</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>(type)(:)</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.other.attribute-name.dtk-symbols keyword.declaration.type.dtk-symbols</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>punctuation.separator.key-value.dtk-symbols</string>
								</dict>
							</dict>
							<key>contentName</key>
							<string>storage.type.dtk-symbols</string>
							<key>end</key>
							<string>(?=\s)</string>
							<key>name</key>
							<string>meta.symbol.attribute-list.attribute.dtk-symbols</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>(size)(:)</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.other.attribute-name.dtk-symbols keyword.other.dtk-symbols</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>punctuation.separator.key-value.dtk-symbols</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(?=\s)</string>
							<key>name</key>
							<string>meta.symbol.attribute-list.attribute.dtk-symbols</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#numbers</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>(align)(:)</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.other.attribute-name.dtk-symbols</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>punctuation.separator.key-value.dtk-symbols</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(?=\s)</string>
							<key>name</key>
							<string>meta.symbol.attribute-list.attribute.dtk-symbols</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#numbers</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>(\w+)(:)</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.other.attribute-name.dtk-symbols</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>punctuation.separator.key-value.dtk-symbols</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(?=\s)</string>
							<key>name</key>
							<string>meta.symbol.attribute-list.attribute.dtk-symbols</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>match</key>
									<string>\w+</string>
									<key>name</key>
									<string>string.unquoted.dtk-symbols</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>match</key>
							<string>\w+</string>
							<key>name</key>
							<string>meta.symbol.attribute-list.attribute.dtk-symbols entity.other.attribute-name.dtk-symbols</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\s*(#|//)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.dtk-splits</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$</string>
					<key>name</key>
					<string>comment.line.dtk-splits</string>
				</dict>
			</array>
		</dict>
		<key>numbers</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.base.dtk-symbols</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.value.dtk-symbols</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(0[Xx])([[:xdigit:]]*)</string>
					<key>name</key>
					<string>meta.number.integer.hexadecimal.dtk-symbols</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\d+</string>
					<key>name</key>
					<string>meta.number.integer.decimal.dtk-symbols constant.numeric.value.dtk-symbols</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.dtk-symbols</string>
</dict>
</plist>
