<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>splits.txt</string>
	</array>
	<key>name</key>
	<string>decomp-toolkit splits.txt</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(Sections)(:)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.section-def.dtk-splits</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.dtk-splits</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=^\s*[^\s:]+:)</string>
			<key>name</key>
			<string>meta.section-def.dtk-splits</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#section-defs</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*([^\s:]+)(:)</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>meta.split.file.dtk-splits</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.other.split.file-name.dtk-splits entity.name.namespace.dtk-splits</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.separator.dtk-splits</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=^\s*[^\s:]+:)</string>
			<key>name</key>
			<string>meta.split.dtk-splits</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#splits</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>#</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.dtk-splits</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$</string>
					<key>name</key>
					<string>comment.line.number-sign.dtk-splits</string>
				</dict>
			</array>
		</dict>
		<key>numbers</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.base.dtk-splits</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.value.dtk-splits</string>
						</dict>
					</dict>
					<key>match</key>
					<string>\b(0[Xx])([[:xdigit:]]*)</string>
					<key>name</key>
					<string>meta.number.integer.hexadecimal.dtk-splits</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\d+</string>
					<key>name</key>
					<string>meta.number.integer.decimal.dtk-splits constant.numeric.value.dtk-splits</string>
				</dict>
			</array>
		</dict>
		<key>section-def-attrs</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(type)(:)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.type.dtk-splits</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.dtk-splits</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\s)</string>
					<key>name</key>
					<string>meta.section-def.attribute.dtk-splits</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\w+</string>
							<key>name</key>
							<string>string.unquoted.dtk-splits</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(align)(:)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.align.dtk-splits</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.dtk-splits</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\s)</string>
					<key>name</key>
					<string>meta.section-def.attribute.dtk-splits</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#numbers</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\w+)(:)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.dtk-splits</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.dtk-splits</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\s)</string>
					<key>name</key>
					<string>meta.section-def.attribute.dtk-splits</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\w+</string>
							<key>name</key>
							<string>string.unquoted.dtk-splits</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>\w+</string>
					<key>name</key>
					<string>meta.section-def.attribute.dtk-splits entity.other.attribute-name.dtk-splits</string>
				</dict>
			</array>
		</dict>
		<key>section-defs</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?&lt;=\s)(\.init|extabindex|extab|\.(?:text|[cd]tors|(?:ro)?data|bss|s?(?:data|bss)2?))(?=\s)</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>entity.name.section.dtk-splits constant.language.section.dtk-splits</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#section-def-attrs</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\S+</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>entity.name.section.dtk-splits</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#section-def-attrs</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>split-attrs</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(start|end)(:)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.location.dtk-splits keyword.other.location.dtk-splits</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.dtk-splits</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\s)</string>
					<key>name</key>
					<string>meta.split.attribute.dtk-splits</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#numbers</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(rename)(:)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.rename.dtk-splits</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.dtk-splits</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\s)</string>
					<key>name</key>
					<string>meta.split.attribute.dtk-splits</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\S+</string>
							<key>name</key>
							<string>string.unquoted.dtk-splits</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(align)(:)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.align.dtk-splits</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.dtk-splits</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\s)</string>
					<key>name</key>
					<string>meta.split.attribute.dtk-splits</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#numbers</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\w+)(:)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.dtk-splits</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.dtk-splits</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(?=\s)</string>
					<key>name</key>
					<string>meta.split.attribute.dtk-splits</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\S+</string>
							<key>name</key>
							<string>string.unquoted.dtk-splits</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>\w+</string>
					<key>name</key>
					<string>meta.split.attribute.dtk-splits entity.other.attribute-name.dtk-splits</string>
				</dict>
			</array>
		</dict>
		<key>split-sections</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?&lt;=\s)(\.init|extabindex|extab|\.(?:text|[cd]tors|(?:ro)?data|bss|s?(?:data|bss)2?))(?=\s)</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>entity.name.section.dtk-splits constant.language.section.dtk-splits</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#split-attrs</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\S+</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>entity.name.section.dtk-splits</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#split-attrs</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>splits</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?&lt;=:)</string>
					<key>end</key>
					<string>$</string>
					<key>name</key>
					<string>meta.split.file.dtk-splits</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>(order)(:)</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.other.attribute-name.order.dtk-splits</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>punctuation.separator.dtk-splits</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(?=\s)</string>
							<key>name</key>
							<string>meta.split.file.attribute.dtk-splits</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#numbers</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>(\w+)(:)</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.other.attribute-name.dtk-splits</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>punctuation.separator.dtk-splits</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(?=\s)</string>
							<key>name</key>
							<string>meta.split.file.attribute.dtk-splits</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>match</key>
									<string>\S+</string>
									<key>name</key>
									<string>string.unquoted.dtk-splits</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>match</key>
							<string>\w+</string>
							<key>name</key>
							<string>meta.split.file.attribute.dtk-splits entity.other.attribute-name.dtk-splits</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#split-sections</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.dtk-splits</string>
</dict>
</plist>
